### ISSUE TITLE
属性名称比如stoke_color，和自己项目里的冲突

### ISSUE THREAD

**Issue by CK875430315** [GcsSloop/rclayout#15]

**Comment by GcsSloop** [comment]
这种属性名冲突，一般只能是改属性名了，你可以下载源码，然后修改一下属性名称，重新编一个。

**Comment by CK875430315** [comment]
还有一个问题，我在RCRelativeLayout这个的布局里加了一个imageview和一个textview，RCRelativeLayout里有这个属性：app:round_corner="15dp"；但是发现15dp的圆角只作用于imageview和textview，并不是作用于RCRelativeLayout，

**Comment by CK875430315** [comment]
知道问题的了，clip_background这个属性设置为true，就裁剪RCRelativeLayout自身为圆角了，打扰了
