### ISSUE TITLE
大佬，为什么我升级到1.6的最新版本圆角都变成放的了：）

### ISSUE THREAD

**Issue by Adaclass** [GcsSloop/rclayout#18]
以前是1.4的版本

**Comment by GcsSloop** [comment]
设置背景了吗？如果加了背景，设置 clip_background=true.
之前是默认剪裁背景的，后面版本取消了对背景的默认剪裁。

**Comment by guguangzhu** [comment]
我把 mClipBackground改成true 圆角10dp  背景也是方的

**Comment by GcsSloop** [comment]
demo 显示正常吗？

**Comment by GcsSloop** [comment]
![](http://ww1.sinaimg.cn/large/005Xtdi2gy1frc3cgoco9j30gq0aggnx.jpg)
