### ISSUE TITLE
这种实现思路很早就尝试过了，后面因为锯齿问题放弃。

### ISSUE THREAD

**Issue by wurensen** [GcsSloop/rclayout#2]
实现圆形、圆角，一开始也想过这种实现方式，通用。但是效果不理想，锯齿很严重，最终放弃。这也是为什么那么多圆形圆角实现方法不采用该方式的原因。

**Comment by GcsSloop** [comment]
你用的是clip吧。

使用 Paint 的 Xfermode 是没有锯齿的。

```
v1.1.0
更新圆角实现方式。
添加抗锯齿。
```

**Comment by wurensen** [comment]
我刚也在找之前的提交记录，忘了是掉到什么坑里面，最后放弃了~
