### ISSUE TITLE
边框颜色属性stroke_color，设置后，不显示颜色。。。

### ISSUE THREAD

**Issue by Adaclass** [GcsSloop/rclayout#21]

**Comment by GcsSloop** [comment]
有demo吗，具体运行环境，设备型号版本可以发一下吗。

**Comment by GcsSloop** [comment]
另外 stroke_width 属性设置了吗，如果没有设置，默认是 0 dp，也就不会有内容显示出来。

**Comment by Adaclass** [comment]
华为手机Nova 3e，Android8.0，宽度也设置了，
![rclayout](https://user-images.githubusercontent.com/30258067/40641823-9a7db092-634d-11e8-89e4-59c8b6ecfab4.png)

**Comment by Adaclass** [comment]
还有，solid_color属性能动态设置吗，在代码中设置setSolidColor="''''

**Comment by GcsSloop** [comment]
在新版本中有设置方法的。

**Comment by GcsSloop** [comment]
直接运行 demo 就没有边框吗。

**Comment by Adaclass** [comment]
有了。。

**Comment by GcsSloop** [comment]
(｡ì _ í｡) 嗯
