### ISSUE TITLE
大佬，华为8.0的图片不显示圆角。。。RCImageView

### ISSUE THREAD

**Issue by Adaclass** [GcsSloop/rclayout#22]
<com.gcssloop.widget.RCImageView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:adjustViewBounds="true"
            android:background="@drawable/bg_750x750"
            android:scaleType="fitXY"
            app:round_corner="5dp"
            app:clip_background="true"/>
预览 有效果的，运行在华为8.0就方了，小米6.0还是圆角

**Comment by GcsSloop** [comment]
可能是华为 8.0 的 xfermode 和标准API有所不同，也可能是硬件加速的问题，暂时设置该圆角控件渲染模式为软件，关闭硬件加速试试。关闭方式参考下面：
[https://github.com/GcsSloop/AndroidNote/issues/7](https://github.com/GcsSloop/AndroidNote/issues/7)
我暂时没有这些机型，无法测试，如果可行，请反馈一下。

**Comment by Adaclass** [comment]
不行

**Comment by GcsSloop** [comment]
demo 也无法显示圆角吗。
只设置 src 是否有圆角。
只设置 background 是否有圆角呢？

**Comment by Adaclass** [comment]
在demo上加了RCImageView运行华为8.0，还是没效果。。
![wmtfs 8hp 8 5c79 8_5o](https://user-images.githubusercontent.com/30258067/40762937-55b2d06c-64d5-11e8-8855-c4bc48723e11.png)

**Comment by GcsSloop** [comment]
RCRelativeLayout 是否也是无效的呢？
就是不对 demo 进行修改是否也是无效的。

**Comment by xiandanin** [comment]
@Adaclass 华为的哪个型号?

**Comment by Adaclass** [comment]
RCRelativeLayout。的设置setRoundAsCircle可以是圆形图片华为ANE - AL00  8.0

**Comment by Adaclass** [comment]
RCRelativeLayout设置圆角可以，有效果

**Comment by GcsSloop** [comment]
嗯嗯，谢谢反馈，如果是这种情况，可能是 RCImageView 的实现方式问题，我去检查一下。

**Comment by GcsSloop** [comment]
代码实现逻辑都是正常的，可能是在华为这个机型上触发了一些特殊的bug。o(╯□╰)o

**Comment by Adaclass** [comment]
大佬，RCImageView在华为8.0是可以圆角的，我的边框设置宽了，挡到了小圆角，取消边框就看到了，哈哈哈，不好意思。。。

**Comment by GcsSloop** [comment]
嗯，虚惊一场。 (｡ì _ í｡)
