### ISSUE TITLE
三星 Galaxy S7Edge设置圆形边缘被切掉

### ISSUE THREAD

**Issue by xiandanin** [GcsSloop/rclayout#34]
![image](https://user-images.githubusercontent.com/17588779/44911185-91d23580-ad58-11e8-8ce5-6c03081b6c77.png)

三星 Galaxy S7Edge
Android 8.0.0 / Oreo / API 26
密度：560 dp / xxxhdpi / 3.5x
精确密度：537.882 * 532.983 dp
屏幕分辨率：1440 * 2560 px
屏幕尺寸：2.7" * 4.8" / 5.5 英寸

**Comment by xiandanin** [comment]
我试了把mEdgeFix改成0可以解决这个问题，那会引起别的问题吗

**Comment by GcsSloop** [comment]
事实证明，这是一个错误的设置，它还会导致 Android 9 上 Path 显示区域不正确的问题。应该是高版本的设备调整了 Path 相关的一些内容。
