### ISSUE TITLE
RCImageView和RCRelativeLayout,设置底部圆角的方法左下和右下弄反了

### ISSUE THREAD

**Issue by dbq4130** [GcsSloop/rclayout#35]
左下和右下弄反了，
之前是
mRCHelper.radii[4] = bottomLeftRadius;
mRCHelper.radii[5] = bottomLeftRadius;
改成
mRCHelper.radii[6] = bottomLeftRadius;
mRCHelper.radii[7] = bottomLeftRadius;

之前是
mRCHelper.radii[6] = bottomRightRadius;
mRCHelper.radii[7] = bottomRightRadius;
改成
mRCHelper.radii[4] = bottomRightRadius;
mRCHelper.radii[5] = bottomRightRadius;

**Comment by GcsSloop** [comment]
谢谢，已经修复。
