### ISSUE TITLE
9.0切背景导致白板

### ISSUE THREAD

**Issue by zkywalker** [GcsSloop/rclayout#44]
9.0切背景导致白板。感觉9.0不是很稳定，有个思路是判断下版本，9.0以后使用setOutlineProvider设置圆角

**Comment by hyyaoming** [comment]
楼上的大兄弟解决了咩？

**Comment by zkywalker** [comment]
> 楼上的大兄弟解决了咩？

说了个解决思路了呀，setOutlineProvider

**Comment by hyyaoming** [comment]
我已经使用cardView代替了，我翻了下cardView的源码，好像也是用你说的这个玩意儿做的。

**Comment by zkywalker** [comment]
> 我已经使用cardView代替了，我翻了下cardView的源码，好像也是用你说的这个玩意儿做的。

嗯处理方式也和card view类似，判断api版本，替换对应的绘制的代理类。具体没看RC的代码不知道是否所有的api都有替换的方式

**Comment by dtdeng** [comment]
个人解决方法，不要clipbackground了，在原布局中加一个ImageView作为背景，希望有帮助

**Comment by zkywalker** [comment]
> 个人解决方法，不要clipbackground了，在原布局中加一个ImageView作为背景，希望有帮助

这个方案解决不了需要切割背景的问题啊

**Comment by helengray** [comment]
public void draw(Canvas canvas) {
        if (mRCHelper.mClipBackground) {
            canvas.saveLayer(mRCHelper.mLayer, null, Canvas.ALL_SAVE_FLAG);//加这句
            canvas.clipPath(mRCHelper.mClipPath);
            super.draw(canvas);
            canvas.restore();
        } else {
            super.draw(canvas);
        }
    }

**Comment by helengray** [comment]
`public void draw(Canvas canvas) {
        if (mRCHelper.mClipBackground) {
            canvas.saveLayer(mRCHelper.mLayer, null, Canvas.ALL_SAVE_FLAG);//加这句
            canvas.clipPath(mRCHelper.mClipPath);
            super.draw(canvas);
            canvas.restore();
        } else {
            super.draw(canvas);
        }
    }`

**Comment by helengray** [comment]
```java
public void draw(Canvas canvas) {
        if (mRCHelper.mClipBackground) {
            canvas.saveLayer(mRCHelper.mLayer, null, Canvas.ALL_SAVE_FLAG);//加这句
            canvas.clipPath(mRCHelper.mClipPath);
            super.draw(canvas);
            canvas.restore();
        } else {
            super.draw(canvas);
        }
    }
```
