### ISSUE TITLE
1.8.1版本构建失败

### ISSUE THREAD

**Issue by zhangyd0227** [GcsSloop/rclayout#45]
> Could not resolve com.gcssloop.widget:rclayout:1.8.1.
  Required by:
      project :app
   > Could not resolve com.gcssloop.widget:rclayout:1.8.1.
      > Could not get resource 'http://lib.gcssloop.com:8081/repository/gcssloop-central/com/gcssloop/widget/rclayout/1.8.1/rclayout-1.8.1.pom'.
         > Could not GET 'http://lib.gcssloop.com:8081/repository/gcssloop-central/com/gcssloop/widget/rclayout/1.8.1/rclayout-1.8.1.pom'.
            > Connect to lib.gcssloop.com:8081 [lib.gcssloop.com/192.157.231.172] failed: Connection refused (Connection refused)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s

**Comment by GcsSloop** [comment]
已经修复
