### ISSUE TITLE
不用用了，clipPath产生的锯齿效果毁所有亮点

### ISSUE THREAD

**Issue by zwping** [GcsSloop/rclayout#47]

**Comment by zwping** [comment]
偶尔发现另外一个圆角布局框架：[GenaralRoundLayout](https://github.com/minminaya/GenaralRoundLayout)，功能不强大但解决了锯齿bug
但我都不用他们
目前项目中使用了是兼容5.0以上的CardView实现圆角布局

**Comment by gfzy9876** [comment]
给mPaint添抗锯齿属性不可以解决问题吗

**Comment by zwping** [comment]
兼容性问题，低版本裁剪没有锯齿，可以参考二楼方案

**Comment by zhengpengzheng** [comment]
1111
