### ISSUE TITLE
当RCRelativeLayout小于40dp时,会出现矩形边框

### ISSUE THREAD

**Issue by xiandanin** [GcsSloop/rclayout#5]
直接跑的Demo，把RCRelativeLayout宽高改成了39dp时,设置为圆形，就会出现矩形边框

![image](https://user-images.githubusercontent.com/17588779/32042248-80676432-b9fc-11e7-9a1a-bba69e3da1b8.png)

**Comment by GcsSloop** [comment]
这个问题在我这边没有复现，看样子像是边缘区域有一个像素的区域没有被遮盖到，所以尝试修复了一下。
你使用最新的 1.4.2 版本看一下是否还存在该问题。

**Comment by xiandanin** [comment]
果然解决了
