### ISSUE TITLE
gradle构建失败

### ISSUE THREAD

**Issue by HibariYo** [GcsSloop/rclayout#51]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.gcssloop.widget:rclayout:1.8.1.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve com.gcssloop.widget:rclayout:1.8.1.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve com.gcssloop.widget:rclayout:1.8.1.
Show Details
Affected Modules: app

**Comment by GcsSloop** [comment]
已经修复
