### ISSUE TITLE
当view超过很长的话  view无法显示

### ISSUE THREAD

**Issue by shike1116** [GcsSloop/rclayout#8]
布局如下
`<ScrollView
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="horizontal">

            <com.test.testandroid.test_round_corner.p2.RCRelativeLayout
                android:id="@+id/frame_container"
                android:layout_width="wrap_content"
                app:round_corner="14dp"
                android:layout_height="wrap_content">

                <ImageView
                    android:id="@+id/img_default"
                    android:layout_width="50dp"
                    android:background="#0000ff"
                    android:layout_height="3000dp"/>
            </com.test.testandroid.test_round_corner.p2.RCRelativeLayout>
        </LinearLayout>
    </ScrollView>`

**Comment by GcsSloop** [comment]
这种超长的情况，暂时不在考虑范围内。😂
